title: Narravit
description: Human-first tools for AI-assisted TTRPG storytelling
tagline: Human-first tools for AI-assisted TTRPG storytelling
url: https://darklight3it.github.io
baseurl: /narravit
remote_theme: "jekyll/minima@4de3223"
markdown: kramdown
show_downloads: false

exclude:
  - _drafts
